# Deployment defintion
apiVersion: apps/v1                              # specifies the API version used for defining a resource in a manifest. v1 means it is a stable version of this API.
kind: Deployment                                 # defines the object to apply the dfinitions
metadata:                                        # metadata of the deployment
  name: flask-app                                # name of the dployment
spec:                                            # specifications of the deployment
  replicas: 5                                    # the number of replicas of pods
  selector:                                      # define how the Deployment obj identifies which Pods it should manage.
    matchLabels:                                 # specifies label-based selection of resources (Pods)
      app: flask-app                             # Only pods with the exact label "app: flask-app" will be selected.
  template:                                      # describes the pod’s metadata and container specifications.
    metadata:                                    # metadata is applied to pods
      labels:                                    # Labels to be assigned to the pods
        app: flask-app                           # `template.metadata.labels` specifies the labels to be assigned to the Pods created by the Deployment. Pods will be created with this label `flask-app`
    spec:                                        # specification for the pod, e.g. specifies the containers in the pod
      containers:                                # list of containers to be deployed and containers' configs
      - name: flask-app                          # name of the conainer to be deployed .
        image: yfrepo/simple-flask-app:latest    # image of the conatiner
        ports:                                   # Defines the ports that the container exposes.
        - containerPort: 5000                    # Specifies that the container listens on port 5000.
---                                              # Object separator. I must be present when there are resource defintions in one yaml file
# Service devinition
apiVersion: v1                                   # Specifies the API version for the resource.
kind: Service                                    # Defines the type of Kubernetes resource.
metadata:                                        # Provides metadata about the resource, like its name, labels, and annotations.
  name: flask-app-service                        # `flask-app-service` - The name assigned to the Service.
spec:                                            # Defines the specification for the Service like behavior or configuration.
  selector:                                      # Determines the Pods this Service will routing traffic to.
    app: flask-app                               # Selects Pods with this label to be associated with the Service.
  ports:                                         # Specifies the ports for the Service
  - protocol: TCP                                # Defines the protocol to be used for communication.
    port: 80                                     # Specifies the port on which the Service will expose itself.
    targetPort: 5000                             # Defines the port on the Pods that the Service will forward traffic to.
  type: NodePort                                 # Service type that exposes your application on a static port on each node of the cluster.
