FROM nginx:1.27.4 as build

WORKDIR /app
COPY package.json server.js /app/
RUN apt update -y && apt install npm -y && npm install


FROM nginx:alpine3.21 as main

COPY --from=build /app /
EXPOSE 4000
CMD ["node", "server.js"]
